dags:
  gitSync:
    enabled: true
    repo: https://github.com/rahulkatlaparthi/airflow-dags.git
    branch: test
    subPath: dags

webserver:
  defaultUser:
    enabled: true
    username: admin
    password: admin
