name: Airflow AKS CI/CD

on:
  push:
    branches:
      - test

jobs:
  deploy-airflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/cli@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      run: |
        az aks get-credentials --resource-group cvx_group --name sample --overwrite-existing
        kubectl config current-context

    - name: Deploy/Upgrade Airflow via Helm
      run: |
        helm repo add apache-airflow https://airflow.apache.org
        helm repo update

        helm upgrade --install airflow apache-airflow/airflow \
          -n airflow --create-namespace \
          -f values.yaml
